apiVersion: v1
kind: Secret
metadata:
  name: postgres-app-secret
  namespace: e-ticket
type: kubernetes.io/basic-auth
stringData:
  username: eticket
  password: nqDKvydsR4BnruK0eToBzOD4NjOEJkA4
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: e-ticket
spec:
  instances: 1

  storage:
    size: 10Gi
    storageClass: local-path

  bootstrap:
    initdb:
      database: e_ticket_system
      owner: eticket
      secret:
        name: postgres-app-secret

  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: postgres-lb
            spec:
              type: LoadBalancer
              ports:
                - name: postgres
                  port: 5432
                  targetPort: 5432

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
